# Section A: Data Structures & Control Structures

#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
lst=[10,20,30,40,50]
print("Original List:", lst)

#append
lst.append(60)
print("After appending:", lst)

#extend
lst.extend([70, 80])
print("After extending:", lst);

#insert
lst.insert(3, 35)
print("After inserting:", lst)

#remove
lst.remove(50)
print("After removing:", lst)

#pop
lst.pop()
print("After popping:", lst)

print("Index of 30:", lst.index(30)) #index
print("Count of 20:", lst.count(20)) #count

#sort
lst.sort()
print("After sorting:", lst)

#reverse
lst.reverse()
print("After reversing:", lst)

#clear
lst.clear()
print("After clearing:", lst)

Original List: [10, 20, 30, 40, 50]
After appending: [10, 20, 30, 40, 50, 60]
After extending: [10, 20, 30, 40, 50, 60, 70, 80]
After inserting: [10, 20, 30, 35, 40, 50, 60, 70, 80]
After removing: [10, 20, 30, 35, 40, 60, 70, 80]
After popping: [10, 20, 30, 35, 40, 60, 70]
Index of 30: 2
Count of 20: 1
After sorting: [10, 20, 30, 35, 40, 60, 70]
After reversing: [70, 60, 40, 35, 30, 20, 10]
After clearing: []


#### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
Stu_tup=("Rashid, Sasank, Sanjay")
Stu_tup[1]="Krishna"

TypeError: 'str' object does not support item assignment

##### It will display the error as "TypeError: 'str' object does not support item assignment".
This is because tuples are immutable, means they cannot be changed after their creation.

#### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
set_int={10,20,30,40,10,30,50,40,80}
print(set_int)

{80, 50, 20, 40, 10, 30}


##### Here sets automatically removes the duplicate values, so that only unique values can be stored.

#### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
person = {
    "name": "Rashid",
    "age": 21,
    "city": "Hyderabad"
}

person["age"]=22
person["email"]="rashidshaik354@gmail.com"

print(person)

{'name': 'Rashid', 'age': 22, 'city': 'Hyderabad', 'email': 'rashidshaik354@gmail.com'}


#### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
age=int(input("Enter your age:"))
if age>=18:
  print("You are eligible to vote")
else:
  print("You are not eligible to vote")

Enter your age:21
You are eligible to vote


#### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [ ]:
marks=int(input("Enter your marks:"))
if marks>=90:
  print("Grade: A")
elif marks>=75 and marks<=89:
  print("Grade: B")
elif marks>=50 and marks<=74:
  print("Grade: C")
else:
  print("Grade: Fail")

Enter your marks:96
Grade: A


#### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num=int(input("Enter a number:"))
if num>0:
  if num%2==0:
    print("Positive and Even Number")
  else:
    print("Positive and Odd Number")
elif num==0:
  print("Number is Zero")
else:
  print("Number is Negative")

Enter a number:8
Positive and Even Number


# Section B: Numpy

#### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [ ]:
import numpy as np

#Scalar using np.array(5)
scalar=np.array(5)
print("Scalar:", scalar)

#1d array with values 1 to 5
arr_1d=np.array([1,2,3,4,5])
print("1D array:", arr_1d)

#2d array(2x3) with values 10 to 60
arr_2d=np.array([[10,20,30],
                 [40,50,60]])
print("2D array:", arr_2d)

Scalar: 5
1D array: [1 2 3 4 5]
2D array: [[10 20 30]
 [40 50 60]]


#### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
import numpy as np

random_array= np.random.randint(0, 101, size=(4,4))
print(" 4x4 random array:\n", random_array)

 4x4 random array:
 [[33 33 75 41]
 [47 17 61 86]
 [ 0 32  4 73]
 [96  6 59 40]]


#### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
import numpy as np
import pandas as pd

array_2d=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
df=pd.DataFrame(array_2d, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


# Section C: Exploring Pandas

#### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [ ]:
import numpy as np
import pandas as pd

data ={
    "Name": ["Rashid", "Sasank", "Nithin", "Charan", "Manogna", "Bindu", "Amrutha", "Keerthana", "Deepthi", "Manasa"],
    "Age": [21,22,23,24,25,26,27,28,29,30],
    "City": ["Hyderabad", "Hyderabad", "Banglore", "Vizag", "Chennai", "Vizag", "Banglore", "Vizag", "Vizag", "Hyderabad"],
    "Salary": [30000, 40000, 50000, 60000, np.nan, 45000, 89000, np.nan, 44000, 70000]
}
df=pd.DataFrame(data)
print(df)

        Name  Age       City   Salary
0     Rashid   21  Hyderabad  30000.0
1     Sasank   22  Hyderabad  40000.0
2     Nithin   23   Banglore  50000.0
3     Charan   24      Vizag  60000.0
4    Manogna   25    Chennai      NaN
5      Bindu   26      Vizag  45000.0
6    Amrutha   27   Banglore  89000.0
7  Keerthana   28      Vizag      NaN
8    Deepthi   29      Vizag  44000.0
9     Manasa   30  Hyderabad  70000.0


In [ ]:
# info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [ ]:
# describe()
df.describe()

Age        Salary
count  10.00000      8.000000
mean   25.50000  53500.000000
std     3.02765  18837.652265
min    21.00000  30000.000000
25%    23.25000  43000.000000
50%    25.50000  47500.000000
75%    27.75000  62500.000000
max    30.00000  89000.000000

In [ ]:
# selecting name and city columns
df[['Name', 'City']]

Name       City
0     Rashid  Hyderabad
1     Sasank  Hyderabad
2     Nithin   Banglore
3     Charan      Vizag
4    Manogna    Chennai
5      Bindu      Vizag
6    Amrutha   Banglore
7  Keerthana      Vizag
8    Deepthi      Vizag
9     Manasa  Hyderabad

In [ ]:
#dropping the city column in pandas
df=df.drop(columns=['City'])
df

Name  Age   Salary
0     Rashid   21  30000.0
1     Sasank   22  40000.0
2     Nithin   23  50000.0
3     Charan   24  60000.0
4    Manogna   25      NaN
5      Bindu   26  45000.0
6    Amrutha   27  89000.0
7  Keerthana   28      NaN
8    Deepthi   29  44000.0
9     Manasa   30  70000.0

In [ ]:
#Fill any missing values in 'Salary' column with the mean
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df

Name  Age   Salary
0     Rashid   21  30000.0
1     Sasank   22  40000.0
2     Nithin   23  50000.0
3     Charan   24  60000.0
4    Manogna   25  53500.0
5      Bindu   26  45000.0
6    Amrutha   27  89000.0
7  Keerthana   28  53500.0
8    Deepthi   29  44000.0
9     Manasa   30  70000.0

In [ ]:
# to remove any duplicate rows
df=df.drop_duplicates()
df

Name  Age   Salary
0     Rashid   21  30000.0
1     Sasank   22  40000.0
2     Nithin   23  50000.0
3     Charan   24  60000.0
4    Manogna   25  53500.0
5      Bindu   26  45000.0
6    Amrutha   27  89000.0
7  Keerthana   28  53500.0
8    Deepthi   29  44000.0
9     Manasa   30  70000.0